#############################
##### Overall workflow ######
#############################

# Build of reference genome (either 'GRCh37' (for b37) or 'GRCh38' (for hg38))
BUILD: "GRCh37"

# Type of input data (either 'Single' or 'Cohort')
DATA: "Cohort"

# Should the pipeline be GPU accelerated where possible? (either 'Yes' or 'No')
GPU_ACCELERATED: "Yes"

# Should the data be prepared to be ingested into scout? (either 'Yes' or 'No')
PREPARE_FOR_SCOUT: "Yes"

# File paths to the reference genome (.fasta)
REFGENOME: "/NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/human_g1k_v37_decoy.fasta"

# File path to dbSNP database
dbSNP: "/NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/dbsnp_138.b37.vcf"

# Temporary file directory
TEMPDIR: "/NGS/scratch/KSCBIOM/HumanGenomics/tmp/"

# Whole exome sequence settings (leave blank if analysing other data such as whole genome sequence data)
WES:
  # File path to the exome capture regions over which to operate (prefix with the '-L' flag)
  INTERVALS: ""
  # Padding (in bp) to add to each region (prefix with the '-ip' flag)
  PADDING: ""

##############################
##### Pipeline resources #####
##############################

# Number of threads to use per rule/sample for multithreaded rules, multithreading will significantly speed up these rules (diminishing speed gains beyond 8 threads)
THREADS: 8 

# Maximum memory usage per rule/sample (eg. '40g' for 40 gigabytes, this should suffice for exomes)
MAXMEMORY: "80g"

# Maximum number of GPU's to be used per rule/sample for gpu-accelerated runs (eg `1` for 1 GPU)
GPU: 1

##############################
###### Variant filtering #####
##############################

# Tranche filtering level/truth sensitivity
TRANCHE:
  SNPS: "99.95"
  INDELS: "99.4"

###############################################
###### Variant filtering - SINGLE SAMPLES #####
###############################################

# Filtering for single sample analyses
# If NOT analysing single sample data, leave this section blank
# (see more about these settings for gatk FilterVariantTranches at https://gatk.broadinstitute.org/hc/en-us/articles/360042479092-FilterVariantTranches)

SINGLE:

  # Provide a list of resources
  RESOURCES:
    - 
    - 

################################################
###### Variant filtering - COHORT ANALYSIS #####
################################################

# Filtering for cohort analyses
# If NOT analysing cohorts, leave this section blank
# (see more about these settings for gatk VariantRecalibrator at https://gatk.broadinstitute.org/hc/en-us/articles/360042914791-VariantRecalibrator)

COHORT:

  # For indels...
  INDELS:

    # ...provide a list of resources
    RESOURCES:
    - /NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
    - /NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/1000G_phase1.indels.b37.vcf
    - /NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/dbsnp_138.b37.vcf

    # ...provide associated machine learning parameters
    PARAMS:
    - mills,known=false,training=true,truth=true,prior=12.0
    - 1000G,known=false,training=true,truth=false,prior=10.0
    - dbsnp,known=true,training=false,truth=false,prior=2.0

  # For SNP's...
  SNPS:

    # ...provide a list of resources
    RESOURCES:
    - /NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/hapmap_3.3.b37.vcf
    - /NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/1000G_omni2.5.b37.vcf
    - /NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/1000G_phase1.indels.b37.vcf
    - /NGS/scratch/KSCBIOM/HumanGenomics/publicData/gatk_resource_bundle/b37/dbsnp_138.b37.vcf

    # ...provide associated machine learning parameters
    PARAMS:
    - hapmap,known=false,training=true,truth=true,prior=15.0
    - omni,known=false,training=true,truth=false,prior=12.0
    - 1000G,known=false,training=true,truth=false,prior=10.0
    - dbsnp,known=true,training=false,truth=false,prior=2.0

##############################
####### VCF annotation #######
##############################

# File paths to vcf annotation databases
VEP: "/NGS/scratch/KSCBIOM/HumanGenomics/publicData/vep/GRCh37/"
dbNSFP: "/NGS/scratch/KSCBIOM/HumanGenomics/publicData/dbNSFP/GRCh37/dbNSFPv4.0a.hg19.custombuild.gz"
CADD: "/NGS/scratch/KSCBIOM/HumanGenomics/publicData/CADD/GRCh37/whole_genome_SNVs.tsv.gz"